# Generated by Django 2.0.2 on 2018-02-21 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternInRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('design_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatternBuddy.DesignPattern')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatternBuddy.Repository')),
            ],
        ),
    ]
