# Generated by Django 2.0.2 on 2018-02-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0002_patterninrepo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patterninrepo',
            options={'verbose_name_plural': 'patterns in repos'},
        ),
    ]
