# Generated by Django 2.0.2 on 2018-02-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0003_auto_20180220_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
