# Generated by Django 2.0.3 on 2018-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0005_auto_20180319_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='url',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
