# Generated by Django 2.0.3 on 2018-03-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0007_auto_20180319_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFileWithPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifications_count', models.PositiveIntegerField(default=1)),
                ('class_name', models.CharField(default='ClassName', max_length=200)),
                ('url', models.URLField(default='https://github.com')),
                ('role', models.CharField(default='role', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='patterninrepo',
            name='file_name',
        ),
        migrations.AddField(
            model_name='patterninrepo',
            name='modifications_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classfilewithpattern',
            name='pattern_in_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatternBuddy.PatternInRepo'),
        ),
    ]
