# Generated by Django 2.0.2 on 2018-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0008_auto_20180320_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='contributors_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
