# Generated by Django 2.0.2 on 2018-04-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0011_repository_dp_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patterninrepo',
            name='modifications_count',
        ),
    ]
