# Generated by Django 2.0.2 on 2018-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatternBuddy', '0012_remove_patterninrepo_modifications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='dp_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
